language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - PLUGIN_NAME=Lampager
    - REQUIRE=
    - CODECOVERAGE=1
    - CAKE_REF=2.x
    - DB=mysql

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - composer global remove "phpunit/phpunit"
  - composer global require "phpunit/phpunit:<6.0.0"
  - echo "require_once __DIR__ . '/../vendor/autoload.php';" >> ../cakephp/app/Config/bootstrap.php

script:
  - ../travis/script.sh

after_success:
  - cd ../cakephp/app/Plugin/$PLUGIN_NAME
  - mkdir -p build/logs
  - mv ../../clover.xml build/logs
  - travis_retry $TRAVIS_BUILD_DIR/vendor/bin/coveralls
