language: php

php:
  - 5.6
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql
  - postgresql

env:
  global:
    - PLUGIN_NAME=Lampager
    - REQUIRE=
    - CODECOVERAGE=1
    - CAKE_REF=2.x
    - COVERALLS_PARALLEL=true
  jobs:
    - DB=mysql
    - DB=pgsql
    - DB=sqlite

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - sed -i -E "s/(\s*)(.*)('Database\/Postgres',)/\1\2\3\n\1'flags' => array(PDO::ATTR_STRINGIFY_FETCHES => true),/" ../travis/database.php
  - ../travis/before_script.sh
  - composer global remove "phpunit/phpunit"
  - composer global require "phpunit/phpunit:<6.0.0"
  - echo "require_once __DIR__ . '/../vendor/autoload.php';" >> ../cakephp/app/Config/bootstrap.php

script:
  - ../travis/script.sh

after_success:
  - cd ../cakephp/app/Plugin/$PLUGIN_NAME
  - mkdir -p build/logs
  - mv ../../clover.xml build/logs
  - travis_retry ../../vendor/bin/coveralls

notifications:
  webhooks: https://coveralls.io/webhook
