language: php
php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/cake test app All --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
